language: go
go:
- 1.11.x

dist: xenial
sudo: required

# Force-enable Go modules. This will be unnecessary when Go 1.12 lands.
env:
- CHANGE_MINIKUBE_NONE_USER=true INSTALL_K8S_TOOLS=1 RUN_DEP=1 IMG=kiwigrid/gcp-serviceaccount-controller

git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

# Anything in before_script that returns a nonzero exit code will flunk the
# build and immediately stop. It's sorta like having set -e enabled in bash.
# Make sure golangci-lint is vendored.

before_script:
- ./tools/travis/start-kubeadm-dind.sh
- ./tools/travis/k8s-tools.sh
- ./tools/travis/minikube-install.sh

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - make

deploy:
- provider: script
  script: bash ./tools/travis/deploy.sh
  on:
    branch: master
- provider: script
  script: bash ./tools/travis/deploy.sh $TRAVIS_TAG
  on:
    tags: true