required = [
    "github.com/emicklei/go-restful",
    "github.com/onsi/ginkgo", # for test framework
    "github.com/onsi/gomega", # for test matchers
    "k8s.io/client-go/plugin/pkg/client/auth/gcp", # for development against gcp
    "k8s.io/code-generator/cmd/client-gen", # for go generate
    "k8s.io/code-generator/cmd/deepcopy-gen", # for go generate
    "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
    "sigs.k8s.io/controller-runtime/pkg/client/config",
    "sigs.k8s.io/controller-runtime/pkg/controller",
    "sigs.k8s.io/controller-runtime/pkg/handler",
    "sigs.k8s.io/controller-runtime/pkg/manager",
    "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
    "sigs.k8s.io/controller-runtime/pkg/source",
    "sigs.k8s.io/testing_frameworks/integration", # for integration testing
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1",
	"golang.org/x/oauth2",
	"google.golang.org/api/iam/v1",
	"github.com/hashicorp/go-gcp-common/gcputil",
	"github.com/hashicorp/go-cleanhttp",
	"github.com/hashicorp/errwrap",
	"github.com/hashicorp/vault-plugin-secrets-gcp/plugin/iamutil",
    ]

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-gcp-common"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-cleanhttp"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/errwrap"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/vault-plugin-secrets-gcp"

[prune]
  go-tests = true


# STANZAS BELOW ARE GENERATED AND MAY BE WRITTEN - DO NOT MODIFY BELOW THIS LINE.

[[constraint]]
  name="sigs.k8s.io/controller-runtime"
  version="v0.1.1"

[[constraint]]
  name="sigs.k8s.io/controller-tools"
  version="v0.1.1"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"
