apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: gcpnamespacerestrictions.gcp.kiwigrid.com
spec:
  group: gcp.kiwigrid.com
  names:
    kind: GcpNamespaceRestriction
    plural: gcpnamespacerestrictions
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            namespace:
              type: string
            regex:
              type: boolean
            restrictions:
              items:
                properties:
                  resource:
                    type: string
                  roles:
                    items:
                      type: string
                    type: array
                required:
                - resource
                - roles
                type: object
              type: array
          required:
          - namespace
          - regex
          type: object
        status:
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
