// +build !ignore_autogenerated

// Code generated by main. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcpRoleBindings) DeepCopyInto(out *GcpRoleBindings) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcpRoleBindings.
func (in *GcpRoleBindings) DeepCopy() *GcpRoleBindings {
	if in == nil {
		return nil
	}
	out := new(GcpRoleBindings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcpServiceAccount) DeepCopyInto(out *GcpServiceAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcpServiceAccount.
func (in *GcpServiceAccount) DeepCopy() *GcpServiceAccount {
	if in == nil {
		return nil
	}
	out := new(GcpServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GcpServiceAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcpServiceAccountList) DeepCopyInto(out *GcpServiceAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GcpServiceAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcpServiceAccountList.
func (in *GcpServiceAccountList) DeepCopy() *GcpServiceAccountList {
	if in == nil {
		return nil
	}
	out := new(GcpServiceAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GcpServiceAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcpServiceAccountSpec) DeepCopyInto(out *GcpServiceAccountSpec) {
	*out = *in
	if in.GcpRoleBindings != nil {
		in, out := &in.GcpRoleBindings, &out.GcpRoleBindings
		*out = make([]GcpRoleBindings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcpServiceAccountSpec.
func (in *GcpServiceAccountSpec) DeepCopy() *GcpServiceAccountSpec {
	if in == nil {
		return nil
	}
	out := new(GcpServiceAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcpServiceAccountStatus) DeepCopyInto(out *GcpServiceAccountStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcpServiceAccountStatus.
func (in *GcpServiceAccountStatus) DeepCopy() *GcpServiceAccountStatus {
	if in == nil {
		return nil
	}
	out := new(GcpServiceAccountStatus)
	in.DeepCopyInto(out)
	return out
}
