# permissions for end users to edit gcpnamespacerestrictions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcpnamespacerestriction-editor-role
rules:
- apiGroups:
  - gcp.kiwigrid.com
  resources:
  - gcpnamespacerestrictions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gcp.kiwigrid.com
  resources:
  - gcpnamespacerestrictions/status
  verbs:
  - get
