# permissions for end users to view gcpnamespacerestrictions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcpnamespacerestriction-viewer-role
rules:
- apiGroups:
  - gcp.kiwigrid.com
  resources:
  - gcpnamespacerestrictions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gcp.kiwigrid.com
  resources:
  - gcpnamespacerestrictions/status
  verbs:
  - get
