# permissions for end users to view gcpserviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcpserviceaccount-viewer-role
rules:
- apiGroups:
  - gcp.kiwigrid.com
  resources:
  - gcpserviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gcp.kiwigrid.com
  resources:
  - gcpserviceaccounts/status
  verbs:
  - get
