# permissions for end users to edit gcpserviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcpserviceaccount-editor-role
rules:
- apiGroups:
  - gcp.kiwigrid.com
  resources:
  - gcpserviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gcp.kiwigrid.com
  resources:
  - gcpserviceaccounts/status
  verbs:
  - get
